---
- name: Add PostgreSQL 17 repository
  shell: |
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
  changed_when: false

- name: Import the repository signing key
  shell: |
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
  changed_when: false

- name: Update apt cache
  apt:
    update_cache: yes


- name: Ensure PostgreSQL Python libraries are installed.
  pacman:
    name: "{{ postgresql_python_library }}"
    state: present

- name: Ensure PostgreSQL packages are installed.
  pacman:
    name: "{{ postgresql_packages }}"
    state: present

- name: Ensure all configured locales are present.
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ postgresql_locales }}"
  register: locale_gen_result

- name: Force-restart PostgreSQL after new locales are generated.
  systemd:
    name: "{{ postgresql_daemon }}"
    state: restarted
  when: locale_gen_result.changed
